### ISSUE TITLE
Can't retrieve data from DataBroker at HXN. Needs to be resolved ASAP!

### ISSUE THREAD

**Issue by hanfeiyan** [NSLS-II/Bug-Reports#21]
Can't retrieve data from DataBroker for a specific large scan (#1994). It complains the size of data is too big. Needs to be resolved ASAP. See below message

``` python
In [155]: plot2dfly(1994, clim=[60,220],cmap='Oranges')
---------------------------------------------------------------------------
OperationFailure                          Traceback (most recent call last)
<ipython-input-155-263eed7d7ff4> in <module>()
----> 1 plot2dfly(1994, clim=[60,220],cmap='Oranges')

/home/xf03id/ipython_ophyd/profile_xf03id/startup/60-viewer2d.py in plot2dfly(scan_id, x, y, clim, fill_events, cmap)
    114         else:
    115             data = DataBroker.fetch_events(hdr, fill=fill_events)
--> 116             dm = DataMuxer.from_events(data)
    117             df = dm.to_sparse_dataframe()
    118             data_cache[scan_id] = df

/home/xf03id/Repos/dataportal/dataportal/muxer/data_muxer.pyc in from_events(cls, events, verbose)
    333 
    334         instance = cls()
--> 335         instance.append_events(events, verbose)
    336         return instance
    337 

/home/xf03id/Repos/dataportal/dataportal/muxer/data_muxer.pyc in append_events(self, events, verbose)
    344             list of Events (any objects with the expected attributes will do)
    345         """
--> 346         for idx, event in enumerate(events):
    347             if verbose and idx % 25 == 0:
    348                 print('loading event %s' % idx),

/home/xf03id/Repos/dataportal/dataportal/broker/simple_broker.pyc in fetch_events(cls, headers, fill)
    120                 run_start=header.run_start_uid)
    121             for descriptor in descriptors:
--> 122                 for event in find_events(descriptor=descriptor):
    123                     if fill:
    124                         fill_event(event)

/home/xf03id/Repos/metadatastore/metadatastore/commands.pyc in <genexpr>(***failed resolving arguments***)
    808 
    809     _as_document = _AsDocumentRaw()
--> 810     return (reorganize_event(_as_document(name, ev, dref_dict))
    811             for ev in events)
    812 

/nfs/xf03id/mc/envs/ophyd/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/queryset/queryset.pyc in _iter_results(self)
     79                 raise StopIteration
     80             if len(self._result_cache) <= pos:
---> 81                 self._populate_cache()
     82 
     83     def _populate_cache(self):

/nfs/xf03id/mc/envs/ophyd/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/queryset/queryset.pyc in _populate_cache(self)
     91             try:
     92                 for i in xrange(ITER_CHUNK_SIZE):
---> 93                     self._result_cache.append(self.next())
     94             except StopIteration:
     95                 self._has_more = False

/nfs/xf03id/mc/envs/ophyd/lib/python2.7/site-packages/mongoengine-0.8.7-py2.7.egg/mongoengine/queryset/base.pyc in next(self)
   1135             raise StopIteration
   1136 
-> 1137         raw_doc = self._cursor.next()
   1138         if self._as_pymongo:
   1139             return self._get_as_pymongo(raw_doc)

/nfs/xf03id/mc/envs/ophyd/lib/python2.7/site-packages/pymongo/cursor.pyc in next(self)
   1074             raise StopIteration
   1075         db = self.__collection.database
-> 1076         if len(self.__data) or self._refresh():
   1077             if self.__manipulate:
   1078                 return db._fix_outgoing(self.__data.popleft(),

/nfs/xf03id/mc/envs/ophyd/lib/python2.7/site-packages/pymongo/cursor.pyc in _refresh(self)
   1018                               self.__skip, ntoreturn,
   1019                               self.__query_spec(), self.__fields,
-> 1020                               self.__uuid_subtype))
   1021             if not self.__id:
   1022                 self.__killed = True

/nfs/xf03id/mc/envs/ophyd/lib/python2.7/site-packages/pymongo/cursor.pyc in __send_message(self, message)
    956                                                 self.__tz_aware,
    957                                                 self.__uuid_subtype,
--> 958                                                 self.__compile_re)
    959         except OperationFailure:
    960             self.__killed = True

/nfs/xf03id/mc/envs/ophyd/lib/python2.7/site-packages/pymongo/helpers.pyc in _unpack_response(response, cursor_id, as_class, tz_aware, uuid_subtype, compile_re)
    111                                error_object.get("$err"),
    112                                error_object.get("code"),
--> 113                                error_object)
    114 
    115     result = {}

OperationFailure: database error: too much data for sort() with no index.  add an index or specify a smaller limit
```

**Comment by danielballan** [comment]
Can you reproduce this issue on any other scans? Do you have any ideas
about what might be special about this scan? How many datapoints do you
expect that it contain?

**Comment by hanfeiyan** [comment]
There are 65001 data points for this scan. I tested scans with smaller dataset ~10201 points. It works just fine.

Hanfei

**Comment by hanfeiyan** [comment]
I tried several scans. Cut the size by half doesn't work either.

Hanfei

**Comment by danielballan** [comment]
OK, thanks.

The error, as you may already understand, occurs because we sort datapoints (to be precise, Event Documents) on their way out of the database. To facilitate that sorting, we should create an index of the Event time.

We know how to do this non-disruptively, but @ericdill, @tacaswell, and I currently in an airplane on our way to Austin. With your permission, we can try to fix this remotely in the next couple days, but our ability to handle some unexpected problem is limited. Would you like us to try, or would you rather wait for our return, a week from Tuesday?

**Comment by hanfeiyan** [comment]
If you can help extract scan 1994, please try. I need the data right away. The permanent solution can be later.

Thanks.

Hanfei

**Comment by danielballan** [comment]
Understood. We'll take a shot at it in the next hour.

**Comment by danielballan** [comment]
Fixed. After applying the fix, we tried loading scan 1994 and it worked. It
takes about 45 seconds to retrieve the data, but it works. The fix applies
to all scans, not only 1994.

Dan

**Comment by hanfeiyan** [comment]
Thanks a lot for the help and quick response! Now it seems load the data,
but I still can't plot it using plotfly2d. It loads and plots scan 1993
correctly. Any idea?

## In [20]: plot2dfly(1994, clim=[60,220],cmap='Oranges')

ValueError                                Traceback (most recent call last)
<ipython-input-20-263eed7d7ff4> in <module>()
----> 1 plot2dfly(1994, clim=[60,220],cmap='Oranges')

/home/xf03id/ipython_ophyd/profile_xf03id/startup/60-viewer2d.py in
plot2dfly(scan_id, x, y, clim, fill_events, cmap)
    128         else:
    129             break
--> 130     spectrum2 = spectrum.reshape((-1, idx+1))
    131     if clim is None:
    132         clim = (np.nanmin(spectrum2), np.nanmax(spectrum2))

ValueError: total size of new array must be unchanged

Hanfei

**Comment by tacaswell** [comment]
The scan does not look like it is rectangular/complete as there are 65001
events

**Comment by danielballan** [comment]
Consider looking at the source for plotfly2d and writing something simpler
to build up what you need. Maybe the fly direction is different than that
function assumes?

**Comment by hanfeiyan** [comment]
There are in total 141 x 461 = 65001 points. It is broken down to small
blocks to avoid a limit of 16k points on our file system. Ken wrote the
plot program to assemble the loaded data correctly and plot them. It is a
nice NSLS-II logo image we'd like to show tomorrow. If you have no idea,
I'll ask Ken about it tomorrow.

Hanfei

**Comment by klauer** [comment]
The scan data was stored properly and now is retrieved correctly with the fixes. Marking this as closed - thanks for the help, guys.
