### ISSUE TITLE
Jupyter can't convert to PDF file

### ISSUE THREAD

**Issue by yugangzhang** [NSLS-II/Bug-Reports#48]
When try to download the jupyter notebook as a PDF file, I got a error message:

nbconvert failed: Pandoc wasn't found.
Please check that pandoc is installed:
http://johnmacfarlane.net/pandoc/installing.html

**Comment by ericdill** [comment]
Apt-get install pandoc on jupyterhub. I would do it but I don't have sudo rights on jupyterhub :(...  Cc @danielballan

**Comment by yugangzhang** [comment]
I also don't have sudo permission.

**Comment by yugangzhang** [comment]
if I do this

``` python
yuzhang@xf11id-srv1:~$ source activate user_analysis                                                        
discarding /opt/conda/bin from PATH                                                                         
prepending /home/yuzhang/.conda/envs/user_analysis/bin to PATH                                              
(user_analysis)yuzhang@xf11id-srv1:~$ sudo apt-get install pandoc                                           
[sudo] password for yuzhang:                                                                                
Reading package lists... Done                                                                               
Building dependency tree                                                                                    
Reading state information... Done                                                                           
The following extra packages will be installed:                                                             
  pandoc-data                                                                                               
Suggested packages:                                                                                         
  texlive-latex-recommended texlive-xetex texlive-luatex pandoc-citeproc etoolbox                           
The following NEW packages will be installed:                                                               
  pandoc pandoc-data                                                                                        
0 upgraded, 2 newly installed, 0 to remove and 14 not upgraded.                                             
Need to get 0 B/4,656 kB of archives.                                                                       
After this operation, 38.5 MB of additional disk space will be used.                                        
Do you want to continue? [Y/n] y       

```

I got:        

``` python

dpkg: warning: 'ldconfig' not found in PATH or not executable                                               
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable                                      
dpkg: error: 2 expected programs not found in PATH or not executable                                        
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin                               
E: Sub-process /usr/bin/dpkg returned an error code (2)  
```

**Comment by klauer** [comment]
Though I believe @ericdill indicated the package needs to be installed on a different machine than xf11id-srv1 (and thus getting around this specific `sudo`-related error message won't help your original issue), here's how to do it anyway:
```
$ sudo su -
# apt-get install pandoc
```

**Comment by stuwilkins** [comment]
you can also do:

export PATH=$PATH:/sbin:/usr/sbin
apt-get install pandoc

You could also add this to `.bashrc` if you like so that you don't get problems. Doing 

`sudo su -` 

is in violation of the NSLS-II controls network access procedures..........

**Comment by klauer** [comment]
@stuwilkins Shows what I know! Removed.

**Comment by stuwilkins** [comment]
@klauer - I think it shows more that the project beam line IRR is still permanently etched on my brain......

**Comment by yugangzhang** [comment]
@stuwilkins Thanks! 
export PATH=$PATH:/sbin:/usr/sbin works for me to  install Pandoc on our xf11id sever. 

I run a user-customer ENV (xf11id-srv1) on jupyter, but, I still can't convert to a pdf file. It seems like that we have to install it on Jupyter sever. Wait for @danielballan 's help.

**Comment by ericdill** [comment]
Does that export path trick not work on jupyterhub?

**Comment by ericdill** [comment]
Or does the export path trick not remove the need for sudo...?

**Comment by yugangzhang** [comment]
No.

``` python

yuzhang@jupyterhub:~$ export PATH=$PATH:/sbin:/usr/sbin                                                     
yuzhang@jupyterhub:~$ apt-get install pandoc                                                                
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)                               
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?                              
yuzhang@jupyterhub:~$                                                                                       

```

**Comment by stuwilkins** [comment]
Sorry:

export PATH=$PATH:/sbin:/usr/sbin
sudo apt-get install install pandoc

You still need to sudo to be able to install… but the install fails because the superuser tools are not in the path.

S

On Oct 31, 2015, at 5:52 PM, Yugang Zhang <notifications@github.com<mailto:notifications@github.com>> wrote:

No.

yuzhang@jupyterhub:~$ export PATH=$PATH:/sbin:/usr/sbin
yuzhang@jupyterhub:~$ apt-get install pandoc
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
yuzhang@jupyterhub:~$

**Comment by danielballan** [comment]
Yes, the PDF export is a function of the single-user server, running on
jupyterhub, not the kernel running on the compute server at xf11id. Please
do not try to hack around sudo jupyterhub. I don't make untested changes
anymore. We have to handle that machine conservatively now that users at
several beamlines are using it regularly.

I'll get to this soon, but not until Mizuki takes a virtual-machine
snapshot in case anything unexpectedly breaks as a result of the change.

**Comment by yugangzhang** [comment]
Thanks!

**Comment by ericdill** [comment]
@yugangzhang -- @danielballan has installed pandoc and tek on jupyterhub, so it is now possible to download notebooks as pdf documents.  Let us know if there are any other issues

**Comment by danielballan** [comment]
Also, you can export to PDF by using your browser's normal Print functionality.

**Comment by yugangzhang** [comment]
The problem occurs again,

```
500 : Internal Server Error
The error was:
nbconvert failed: Pandoc wasn't found.
Please check that pandoc is installed:
http://johnmacfarlane.net/pandoc/installing.html
```

@danielballan is it possible that pandoc and tek has to been reinstalled after your update jupyterhub?

**Comment by danielballan** [comment]
@yugangzhang Yes. I installed it again, so it should work now. Please let me know if it does not. I added `apt-get install pandoc` to our documented procedure, so we should not miss this again.

**Comment by yugangzhang** [comment]
@danielballan  Thanks. But, it still doesn't work, there are two types of errors.

One jupyter notebook says

```
nbconvert failed: Command '['pandoc', '-v']' returned non-zero exit status 1
```

The other one says

```
nbconvert failed: pdflatex not found on PATH
```

**Comment by ghost** [comment]
Do you have  texlive-latex-base installed from Debian mirrors? If not:

sudo apt-get install texlive-latex-base

**Comment by ericdill** [comment]
@arkilic This has to be installed on jupyterhub and @yugangzhang does not have sudo access on jupyterhub

**Comment by ghost** [comment]
Yes, I am aware of that. I don't believe he has sudo access on anything. He can contact the sys admin group or one of us here can pick it up. Replied to document what is wrong and what needs to get fixed
